using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SkinProgress.Models.Entities
{
    /// <summary>
    /// AnalysisResult Entity
    /// 
    /// Represents the output of CLIP analysis on a single selfie.
    /// Stores severity scores, heatmap reference, and analysis metadata.
    /// 
    /// SOLID Principles:
    /// - Single Responsibility: Encapsulates only analysis result data, not image or user
    /// - Dependency Inversion: No direct dependencies on other entities beyond User
    /// 
    /// Database Strategy:
    /// - Index on (UserId, Timestamp DESC) for fast date-range queries (SC-001 performance)
    /// - Index on Id for fast lookup by analysis ID
    /// - Timestamp stored in UTC for consistency
    /// 
    /// Mapping:
    /// - AnalysisResult (entity) ←→ AnalysisResultDto (DTO)
    /// - Manual mapper: See EvolutionAnalyticsService.MapAnalysisResultToDto()
    /// </summary>
    [Table("AnalysisResults")]
    public class AnalysisResult
    {
        /// <summary>Unique identifier for this analysis result</summary>
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>User who owns this analysis</summary>
        [Required]
        public string UserId { get; set; } = string.Empty;

        /// <summary>Associated selfie ID (references Selfie table)</summary>
        [Required]
        public Guid SelfieId { get; set; }

        /// <summary>Timestamp when analysis was performed</summary>
        [Required]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Overall acne severity (0-10 scale).
        /// From CLIP model output; used for trend calculation (FR-001).
        /// Null until analysis completes.
        /// </summary>
        public int? AcneSeverity { get; set; }

        /// <summary>
        /// Overall inflammation severity (0-10 scale).
        /// From CLIP model output; used for trend calculation (FR-001).
        /// </summary>
        public int? InflammationSeverity { get; set; }

        /// <summary>
        /// Overall redness severity (0-10 scale).
        /// From CLIP model output; used for trend calculation (FR-001).
        /// </summary>
        public int? RednessSeverity { get; set; }

        /// <summary>
        /// Forehead-specific severity (0-10 scale).
        /// Used for zone-level analysis in heatmaps and period comparison (FR-007).
        /// </summary>
        public int? ForeheadSeverity { get; set; }

        /// <summary>
        /// Left cheek severity (0-10 scale).
        /// Used for zone-level analysis.
        /// </summary>
        public int? LeftCheekSeverity { get; set; }

        /// <summary>
        /// Right cheek severity (0-10 scale).
        /// Used for zone-level analysis.
        /// </summary>
        public int? RightCheekSeverity { get; set; }

        /// <summary>
        /// Chin severity (0-10 scale).
        /// Used for zone-level analysis.
        /// </summary>
        public int? ChinSeverity { get; set; }

        /// <summary>
        /// Nose severity (0-10 scale).
        /// Used for zone-level analysis.
        /// </summary>
        public int? NoseSeverity { get; set; }

        /// <summary>
        /// Path to heatmap image generated by CLIP analysis.
        /// Format: /selfies/{userId}/{analysisId}/heatmap.png
        /// Rendered in UI for heatmap display (from wwwroot/selfies/).
        /// Null until analysis completes.
        /// </summary>
        public string? HeatmapImageUrl { get; set; }

        /// <summary>
        /// Status of this analysis result.
        /// Values: "Pending", "Completed", "Failed"
        /// Used to filter out incomplete analyses from dashboard (FR-001).
        /// </summary>
        [Required]
        [MaxLength(20)]
        public string Status { get; set; } = "Pending";

        /// <summary>
        /// Error message if analysis failed.
        /// Null if Status is "Completed" or "Pending".
        /// Used for debugging failed analyses.
        /// </summary>
        [MaxLength(500)]
        public string? ErrorMessage { get; set; }

        /// <summary>
        /// When this record was created in database.
        /// Used for audit trail; different from Timestamp (analysis time).
        /// </summary>
        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Last time this record was updated.
        /// Updated when analysis completes or status changes.
        /// </summary>
        public DateTime? UpdatedAt { get; set; }

        // --- New columns for missing features ---

        /// <summary>Progress score (0-100) computed from severity baseline comparison.</summary>
        public int? ProgressScore { get; set; }

        /// <summary>JSON metadata from compensation algorithm (brightness/angle deltas).</summary>
        public string? CompensationMetadata { get; set; }

        /// <summary>JSON array of detected lesion bounding boxes and classifications.</summary>
        public string? LesionData { get; set; }

        /// <summary>JSON map of zone segmentation mask URLs.</summary>
        public string? SegmentationMasks { get; set; }

        /// <summary>Quality warning message when image quality is insufficient.</summary>
        public string? QualityWarning { get; set; }

        /// <summary>URL to front-view heatmap image.</summary>
        public string? HeatmapFrontUrl { get; set; }

        /// <summary>URL to left-view heatmap image.</summary>
        public string? HeatmapLeftUrl { get; set; }

        /// <summary>URL to right-view heatmap image.</summary>
        public string? HeatmapRightUrl { get; set; }

        /// <summary>URL to 3D model (glTF) for this capture.</summary>
        public string? Model3DUrl { get; set; }

        /// <summary>URL to timelapse video generated from this capture onwards.</summary>
        public string? TimelapseUrl { get; set; }
    }
}
