// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkinProgress.Data;

#nullable disable

namespace SkinProgress.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404120041_AddPhotoCaptureSystem")]
    partial class AddPhotoCaptureSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkinProgress.Models.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AcneSeverity")
                        .HasColumnType("integer");

                    b.Property<int?>("ChinSeverity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ForeheadSeverity")
                        .HasColumnType("integer");

                    b.Property<string>("HeatmapImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("InflammationSeverity")
                        .HasColumnType("integer");

                    b.Property<int?>("LeftCheekSeverity")
                        .HasColumnType("integer");

                    b.Property<int?>("NoseSeverity")
                        .HasColumnType("integer");

                    b.Property<int?>("RednessSeverity")
                        .HasColumnType("integer");

                    b.Property<int?>("RightCheekSeverity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SelfieId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SelfieId")
                        .HasDatabaseName("IX_AnalysisResults_SelfieId");

                    b.HasIndex("UserId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AnalysisResults_UserId_Timestamp");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.AuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.Photo", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CaptureDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SelfieCaptures_CaptureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ViewType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("PhotoId");

                    b.HasIndex("FilePath")
                        .IsUnique()
                        .HasDatabaseName("UX_Photo_FilePath")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("MetadataId")
                        .IsUnique();

                    b.HasIndex("SelfieCaptures_CaptureId");

                    b.HasIndex("ViewType")
                        .HasDatabaseName("IX_Photo_ViewType")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("UserId", "CaptureDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Photo_UserId_CaptureDate")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.PhotoMetadata", b =>
                {
                    b.Property<Guid>("MetadataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Brightness")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<DateTime>("CaptureTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompressionQuality")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CompressionRatio")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExifRaw")
                        .HasColumnType("text");

                    b.Property<int>("FaceCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("FaceDetectionConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("normal");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.HasKey("MetadataId");

                    b.HasIndex("Brightness")
                        .HasDatabaseName("IX_PhotoMetadata_Brightness");

                    b.HasIndex("FaceDetectionConfidence")
                        .HasDatabaseName("IX_PhotoMetadata_FaceDetectionConfidence");

                    b.HasIndex("PhotoId")
                        .IsUnique()
                        .HasDatabaseName("UX_PhotoMetadata_PhotoId");

                    b.ToTable("PhotoMetadatas");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.SelfieCapture", b =>
                {
                    b.Property<Guid>("CaptureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CaptureDate")
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FrontPhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LeftPhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RightPhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("partial");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CaptureId");

                    b.HasIndex("CaptureDate")
                        .HasDatabaseName("IX_SelfieCapture_CaptureDate")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("FrontPhotoId")
                        .IsUnique();

                    b.HasIndex("LeftPhotoId")
                        .IsUnique();

                    b.HasIndex("RightPhotoId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_SelfieCapture_UserId")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.HasIndex("UserId", "CaptureDate")
                        .IsUnique()
                        .HasDatabaseName("UX_SelfieCapture_User_Date")
                        .HasFilter("[DeletedAt] IS NULL");

                    b.ToTable("SelfieCaptures");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CurrentStorageUsed")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSelfieAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LoginLockoutUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("StandardStorageQuota")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.UserEmailConfirmationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserEmailConfirmationTokens");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductsUsed")
                        .HasColumnType("text");

                    b.Property<string>("Sensitivities")
                        .HasColumnType("text");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("SkinProgress.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.AuthToken", b =>
                {
                    b.HasOne("SkinProgress.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.Photo", b =>
                {
                    b.HasOne("SkinProgress.Models.Entities.PhotoMetadata", "Metadata")
                        .WithOne("Photo")
                        .HasForeignKey("SkinProgress.Models.Entities.Photo", "MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkinProgress.Models.Entities.SelfieCapture", "SelfieCapture")
                        .WithMany()
                        .HasForeignKey("SelfieCaptures_CaptureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkinProgress.Models.Entities.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("SelfieCapture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.SelfieCapture", b =>
                {
                    b.HasOne("SkinProgress.Models.Entities.Photo", "FrontPhoto")
                        .WithOne()
                        .HasForeignKey("SkinProgress.Models.Entities.SelfieCapture", "FrontPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkinProgress.Models.Entities.Photo", "LeftPhoto")
                        .WithOne()
                        .HasForeignKey("SkinProgress.Models.Entities.SelfieCapture", "LeftPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkinProgress.Models.Entities.Photo", "RightPhoto")
                        .WithOne()
                        .HasForeignKey("SkinProgress.Models.Entities.SelfieCapture", "RightPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SkinProgress.Models.Entities.User", "User")
                        .WithMany("SelfieCaptures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FrontPhoto");

                    b.Navigation("LeftPhoto");

                    b.Navigation("RightPhoto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.UserEmailConfirmationToken", b =>
                {
                    b.HasOne("SkinProgress.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.UserPreferences", b =>
                {
                    b.HasOne("SkinProgress.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.PhotoMetadata", b =>
                {
                    b.Navigation("Photo");
                });

            modelBuilder.Entity("SkinProgress.Models.Entities.User", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("SelfieCaptures");
                });
#pragma warning restore 612, 618
        }
    }
}
